In [28]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位:["國文", "英文", "數學", "自然", "社會", "總分","平均","排名"]
#索引:["學生" + str(i) for i in range(1, 51)]
#建立一個DataFrame
import numpy as np
import pandas as pd

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores, columns=["國文", "英文", "數學", "自然", "社會"],
                      index=["學生" + str(i) for i in range(1, 51)])
    df.index.name = "學生"
    df.columns.name = "科目"
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df["總分"] = sum_values
    df["平均"] = mean_values
    rank_values = df["總分"].rank(method="min", ascending=False)
    df["排名"] = rank_values
    return df
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目     國文  英文   數學   自然   社會   總分    平均    排名
學生
學生1    92  97   50   89   50  378  75.6  22.0
學生2    70  69   50   57   61  307  61.4  50.0
學生3    55  94   72   60   56  337  67.4  42.0
學生4    59  91   90   50   50  340  68.0  41.0
學生5    51  97   77   68   72  365  73.0  31.0
學生6    88  51   80   64  100  383  76.6  18.0
學生7    77  85   67   91   52  372  74.4  26.0
學生8    84  94   65   77   99  419  83.8   6.0
學生9    79  71   78   85   68  381  76.2  19.0
學生10   56  70   80   63   82  351  70.2  38.0
學生11   62  83   96  100   91  432  86.4   3.0
學生12   94  74   93   86   79  426  85.2   5.0
學生13   56  62   84   97   91  390  78.0  13.0
學生14   88  56   91   80   50  365  73.0  31.0
學生15   57  75   83   50   60  325  65.0  48.0
學生16   91  73   74   86   62  386  77.2  17.0
學生17   99  90   81   95   71  436  87.2   2.0
學生18   84  91   88   60   74  397  79.4  11.0
學生19   85  53   88   75   88  389  77.8  14.0
學生20   93  54   59   57   59  322  64.4  49.0
學生21   58  74   69   92   56  349  69.8  39.0
學生22   73  81   54   71   58  337  67.4  42.0
學生23   72  96   96   52   77  393  78.6  12.0
學生24   53  86   83   57   84  363  72.6  34.0
學生25   61  86   51   70   69  337  67.4  42.0
學生26   61  62   95   75   79  372  74.4  26.0
學生27   68  99   86   62   72  387  77.4  16.0
學生28  100  61   50   56   95  362  72.4  35.0
學生29   66  96   77   77   56  372  74.4  26.0
學生30   81  88  100   68   65  402  80.4   9.0
學生31   85  54   93   75   99  406  81.2   8.0
學生32   73  69   71   87   74  374  74.8  24.0
學生33   71  93   77   56   73  370  74.0  30.0
學生34   81  77   55   79   96  388  77.6  15.0
學生35   84  59   78   56   94  371  74.2  29.0
學生36   57  79  100   80   92  408  81.6   7.0
學生37   89  74   80   97   99  439  87.8   1.0
學生38   96  73   79   51   81  380  76.0  20.0
學生39   89  77   52   99   57  374  74.8  24.0
學生40   66  86   53   60   64  329  65.8  46.0
學生41   91  50   89   52   72  354  70.8  37.0
學生42   56  67   79   70   61  333  66.6  45.0
學生43   63  51   79   84   51  328  65.6  47.0
學生44   58  56   80   93   89  376  75.2  23.0
學生45   90  76   65  100   98  429  85.8   4.0
學生46   70  79   70   72   73  364  72.8  33.0
學生47   86  79   86   50   99  400  80.0  10.0
學生48   93  69   59   76   58  355  71.0  36.0
學生49   55  84   93   69   78  379  75.8  21.0
學生50   69  59   54   74   86  342  68.4  40.0

In [29]:
#選擇欄位
df1 = df[["國文", "英文", "數學", "自然", "社會"]]
df1

科目     國文  英文   數學   自然   社會
學生
學生1    92  97   50   89   50
學生2    70  69   50   57   61
學生3    55  94   72   60   56
學生4    59  91   90   50   50
學生5    51  97   77   68   72
學生6    88  51   80   64  100
學生7    77  85   67   91   52
學生8    84  94   65   77   99
學生9    79  71   78   85   68
學生10   56  70   80   63   82
學生11   62  83   96  100   91
學生12   94  74   93   86   79
學生13   56  62   84   97   91
學生14   88  56   91   80   50
學生15   57  75   83   50   60
學生16   91  73   74   86   62
學生17   99  90   81   95   71
學生18   84  91   88   60   74
學生19   85  53   88   75   88
學生20   93  54   59   57   59
學生21   58  74   69   92   56
學生22   73  81   54   71   58
學生23   72  96   96   52   77
學生24   53  86   83   57   84
學生25   61  86   51   70   69
學生26   61  62   95   75   79
學生27   68  99   86   62   72
學生28  100  61   50   56   95
學生29   66  96   77   77   56
學生30   81  88  100   68   65
學生31   85  54   93   75   99
學生32   73  69   71   87   74
學生33   71  93   77   56   73
學生34   81  77   55   79   96
學生35   84  59   78   56   94
學生36   57  79  100   80   92
學生37   89  74   80   97   99
學生38   96  73   79   51   81
學生39   89  77   52   99   57
學生40   66  86   53   60   64
學生41   91  50   89   52   72
學生42   56  67   79   70   61
學生43   63  51   79   84   51
學生44   58  56   80   93   89
學生45   90  76   65  100   98
學生46   70  79   70   72   73
學生47   86  79   86   50   99
學生48   93  69   59   76   58
學生49   55  84   93   69   78
學生50   69  59   54   74   86

In [30]:
s = df1.loc["學生4"]
less_than_60_series = s[s < 60]
#取出不及格的科目
failed_subjects = less_than_60_series.index.tolist()
failed_subjects
#取出不及格的科目分數
failed_subject_scores = less_than_60_series.values.tolist()
failed_subject_scores
#建立一個Series,值要轉換為字串,若有多值則用逗號分隔
failed_subjects = ', '.join(failed_subjects)
failed_subject_scores = ', '.join(map(str, failed_subject_scores))
#建立一個Series,索引為["科目", "分數"]
result_series = pd.Series([failed_subjects, failed_subject_scores], index=["未及格科目", "分數"])
result_series

未及格科目    國文, 自然, 社會
分數       59, 50, 50
dtype: object

In [31]:
def apply_statistics(s):
    less_than_60_series = s[s < 60]
    #不及格科目數量
    failed_subject_count = less_than_60_series.count()
    #取出不及格的科目
    failed_subjects = less_than_60_series.index.tolist()

    #取出不及格的科目分數
    failed_subject_scores = less_than_60_series.values.tolist()
    
    #建立一個Series,值要轉換為字串,若有多值則用逗號分隔
    failed_subjects = ', '.join(failed_subjects)
    failed_subject_scores = ', '.join(map(str, failed_subject_scores))
    return pd.Series([failed_subject_count, failed_subjects, failed_subject_scores], index=["不及格科目數量","未及格科目", "分數"])

df2 = df1.apply(apply_statistics,axis=1)
df2

      不及格科目數量           未及格科目              分數
學生
學生1         2          數學, 社會          50, 50
學生2         2          數學, 自然          50, 57
學生3         2          國文, 社會          55, 56
學生4         3      國文, 自然, 社會      59, 50, 50
學生5         1              國文              51
學生6         1              英文              51
學生7         1              社會              52
學生8         0
學生9         0
學生10        1              國文              56
學生11        0
學生12        0
學生13        1              國文              56
學生14        2          英文, 社會          56, 50
學生15        2          國文, 自然          57, 50
學生16        0
學生17        0
學生18        0
學生19        1              英文              53
學生20        4  英文, 數學, 自然, 社會  54, 59, 57, 59
學生21        2          國文, 社會          58, 56
學生22        2          數學, 社會          54, 58
學生23        1              自然              52
學生24        2          國文, 自然          53, 57
學生25        1              數學              51
學生26        0
學生27        0
學生28        2          數學, 自然          50, 56
學生29        1              社會              56
學生30        0
學生31        1              英文              54
學生32        0
學生33        1              自然              56
學生34        1              數學              55
學生35        2          英文, 自然          59, 56
學生36        1              國文              57
學生37        0
學生38        1              自然              51
學生39        2          數學, 社會          52, 57
學生40        1              數學              53
學生41        2          英文, 自然          50, 52
學生42        1              國文              56
學生43        2          英文, 社會          51, 51
學生44        2          國文, 英文          58, 56
學生45        0
學生46        0
學生47        1              自然              50
學生48        2          數學, 社會          59, 58
學生49        1              國文              55
學生50        2          英文, 數學          59, 54

In [32]:
#df和df2合併
df_merged = pd.concat([df, df2], axis=1)
df_merged

,國文,英文,數學,自然,社會,總分,平均,排名,不及格科目數量,未及格科目,分數
學生,,,,,,,,,,,
學生1,92,97,50,89,50,378,75.6,22.0,2,"數學, 社會","50, 50"
學生2,70,69,50,57,61,307,61.4,50.0,2,"數學, 自然","50, 57"
學生3,55,94,72,60,56,337,67.4,42.0,2,"國文, 社會","55, 56"
學生4,59,91,90,50,50,340,68.0,41.0,3,"國文, 自然, 社會","59, 50, 50"
學生5,51,97,77,68,72,365,73.0,31.0,1,國文,51
學生6,88,51,80,64,100,383,76.6,18.0,1,英文,51
學生7,77,85,67,91,52,372,74.4,26.0,1,社會,52
學生8,84,94,65,77,99,419,83.8,6.0,0,,
學生9,79,71,78,85,68,381,76.2,19.0,0,,
學生10,56,70,80,63,82,351,70.2,38.0,1,國文,56
學生11,62,83,96,100,91,432,86.4,3.0,0,,
學生12,94,74,93,86,79,426,85.2,5.0,0,,
學生13,56,62,84,97,91,390,78.0,13.0,1,國文,56
學生14,88,56,91,80,50,365,73.0,31.0,2,"英文, 社會","56, 50"
學生15,57,75,83,50,60,325,65.0,48.0,2,"國文, 自然","57, 50"
學生16,91,73,74,86,62,386,77.2,17.0,0,,
學生17,99,90,81,95,71,436,87.2,2.0,0,,
學生18,84,91,88,60,74,397,79.4,11.0,0,,
學生19,85,53,88,75,88,389,77.8,14.0,1,英文,53
學生20,93,54,59,57,59,322,64.4,49.0,4,"英文, 數學, 自然, 社會","54, 59, 57, 59"
學生21,58,74,69,92,56,349,69.8,39.0,2,"國文, 社會","58, 56"
學生22,73,81,54,71,58,337,67.4,42.0,2,"數學, 社會","54, 58"
學生23,72,96,96,52,77,393,78.6,12.0,1,自然,52
學生24,53,86,83,57,84,363,72.6,34.0,2,"國文, 自然","53, 57"
學生25,61,86,51,70,69,337,67.4,42.0,1,數學,51
學生26,61,62,95,75,79,372,74.4,26.0,0,,
學生27,68,99,86,62,72,387,77.4,16.0,0,,
學生28,100,61,50,56,95,362,72.4,35.0,2,"數學, 自然","50, 56"
學生29,66,96,77,77,56,372,74.4,26.0,1,社會,56
學生30,81,88,100,68,65,402,80.4,9.0,0,,
學生31,85,54,93,75,99,406,81.2,8.0,1,英文,54
學生32,73,69,71,87,74,374,74.8,24.0,0,,
學生33,71,93,77,56,73,370,74.0,30.0,1,自然,56
學生34,81,77,55,79,96,388,77.6,15.0,1,數學,55
學生35,84,59,78,56,94,371,74.2,29.0,2,"英文, 自然","59, 56"
學生36,57,79,100,80,92,408,81.6,7.0,1,國文,57
學生37,89,74,80,97,99,439,87.8,1.0,0,,
學生38,96,73,79,51,81,380,76.0,20.0,1,自然,51
學生39,89,77,52,99,57,374,74.8,24.0,2,"數學, 社會","52, 57"
學生40,66,86,53,60,64,329,65.8,46.0,1,數學,53
學生41,91,50,89,52,72,354,70.8,37.0,2,"英文, 自然","50, 52"
學生42,56,67,79,70,61,333,66.6,45.0,1,國文,56
學生43,63,51,79,84,51,328,65.6,47.0,2,"英文, 社會","51, 51"
學生44,58,56,80,93,89,376,75.2,23.0,2,"國文, 英文","58, 56"
學生45,90,76,65,100,98,429,85.8,4.0,0,,
學生46,70,79,70,72,73,364,72.8,33.0,0,,
學生47,86,79,86,50,99,400,80.0,10.0,1,自然,50
學生48,93,69,59,76,58,355,71.0,36.0,2,"數學, 社會","59, 58"
學生49,55,84,93,69,78,379,75.8,21.0,1,國文,55
學生50,69,59,54,74,86,342,68.4,40.0,2,"英文, 數學","59, 54"

In [34]:
#df_merged儲存為excel檔
df_merged.to_excel("df_merged.xlsx")