In [12]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位:["國文", "英文", "數學", "自然", "社會", "總分","平均","排名"]
#索引:["學生" + str(i) for i in range(1, 51)]
#建立一個DataFrame
import numpy as np
import pandas as pd

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores, columns=["國文", "英文", "數學", "自然", "社會"],
                      index=["學生" + str(i) for i in range(1, 51)])
    df.index.name = "學生"
    df.columns.name = "科目"
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df["總分"] = sum_values
    df["平均"] = mean_values
    rank_values = df["總分"].rank(method="min", ascending=False)
    df["排名"] = rank_values
    return df

In [13]:
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df
#AI建立一個function
#依據df
#建立1個統計的DataFrame
#欄位: ['國文', '英文', '數學', '自然', '社會']
#欄位: ['平均', '最高', '最低', '中間值']


df

科目     國文  英文   數學   自然  社會   總分    平均    排名
學生
學生1    51  98   74   51  86  360  72.0  34.0
學生2    85  75   98   61  50  369  73.8  26.0
學生3    74  51   85   86  90  386  77.2  17.0
學生4    86  62   60   91  96  395  79.0  10.0
學生5    68  75   65   56  87  351  70.2  41.0
學生6    74  83   89   88  58  392  78.4  12.0
學生7    65  88   59   84  53  349  69.8  42.0
學生8    94  51   58   79  70  352  70.4  39.0
學生9    77  63   68   77  72  357  71.4  37.0
學生10   82  97   98   76  72  425  85.0   2.0
學生11   66  97   81   95  59  398  79.6   9.0
學生12   74  85   69   88  73  389  77.8  14.0
學生13   67  98   67   80  61  373  74.6  22.0
學生14   64  87   82   89  66  388  77.6  15.0
學生15   97  51   93   68  53  362  72.4  30.0
學生16   62  92   96   81  75  406  81.2   8.0
學生17   91  90   95   63  53  392  78.4  12.0
學生18   81  93   80   88  72  414  82.8   5.0
學生19   55  89   78   70  57  349  69.8  42.0
學生20   82  79   62   62  75  360  72.0  34.0
學生21   71  85   76   76  57  365  73.0  28.0
學生22  100  70   69   98  76  413  82.6   6.0
學生23   76  72   82   55  98  383  76.6  19.0
學生24   61  80   53   75  89  358  71.6  36.0
學生25   66  68   90  100  86  410  82.0   7.0
學生26   86  69   55   98  53  361  72.2  33.0
學生27   87  81   95   70  89  422  84.4   3.0
學生28   63  74   70   84  96  387  77.4  16.0
學生29   69  62   59   53  51  294  58.8  49.0
學生30   51  66   72   84  98  371  74.2  25.0
學生31   88  98   52   75  60  373  74.6  22.0
學生32   67  66   88   69  72  362  72.4  30.0
學生33   50  67   90   68  81  356  71.2  38.0
學生34   79  58   90   71  64  362  72.4  30.0
學生35   75  99   64   70  61  369  73.8  26.0
學生36   79  86   54   73  80  372  74.4  24.0
學生37   81  56   52   74  56  319  63.8  47.0
學生38   91  71   78   73  68  381  76.2  20.0
學生39   66  79   78   75  54  352  70.4  39.0
學生40   85  53   81   97  63  379  75.8  21.0
學生41   55  51   51   50  86  293  58.6  50.0
學生42   55  73   83   79  57  347  69.4  44.0
學生43   96  61   88   95  53  393  78.6  11.0
學生44   73  93   91   50  57  364  72.8  29.0
學生45  100  70   92   92  77  431  86.2   1.0
學生46   99  62   97   73  90  421  84.2   4.0
學生47   56  70   59   77  68  330  66.0  46.0
學生48   65  53   71   65  54  308  61.6  48.0
學生49   80  73  100   64  67  384  76.8  18.0
學生50   82  51   69   62  75  339  67.8  45.0

In [14]:
#建立1個統計的DataFrame
def create_statistics_dataframe(df):
    cols = ['國文', '英文', '數學', '自然', '社會']
    stats = df[cols].agg(['mean', 'max', 'min', 'median'])
    stats.index = ['平均', '最高', '最低', '中間值']
    return stats
create_statistics_dataframe(df)

科目       國文     英文      數學      自然     社會
平均    74.94  74.42   76.12   75.56  70.28
最高   100.00  99.00  100.00  100.00  98.00
最低    50.00  51.00   51.00   50.00  50.00
中間值   74.50  73.00   78.00   75.00  69.00