In [1]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位:["國文", "英文", "數學", "自然", "社會", "總分","平均","排名"]
#索引:["學生" + str(i) for i in range(1, 51)]
#建立一個DataFrame
import numpy as np
import pandas as pd

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores, columns=["國文", "英文", "數學", "自然", "社會"],
                      index=["學生" + str(i) for i in range(1, 51)])
    df.index.name = "學生"
    df.columns.name = "科目"
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df["總分"] = sum_values
    df["平均"] = mean_values
    rank_values = df["總分"].rank(method="min", ascending=False)
    df["排名"] = rank_values
    return df
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目     國文  英文  數學   自然   社會   總分    平均    排名
學生
學生1    77  88  78   83   62  388  77.6  17.0
學生2    73  75  54   55   73  330  66.0  44.0
學生3    62  83  66  100   70  381  76.2  20.0
學生4    77  99  54   94   90  414  82.8   7.0
學生5    91  97  50   59   74  371  74.2  26.0
學生6    81  80  67   52   98  378  75.6  22.0
學生7    51  92  99   54   61  357  71.4  35.0
學生8    68  97  50   89   64  368  73.6  29.0
學生9    75  92  72   73  100  412  82.4   8.0
學生10   56  81  72   69   61  339  67.8  41.0
學生11   90  82  73   99   89  433  86.6   3.0
學生12  100  92  93   73   82  440  88.0   1.0
學生13   83  63  98   99   77  420  84.0   6.0
學生14   86  88  62   85   50  371  74.2  26.0
學生15   63  53  61   94   54  325  65.0  46.0
學生16   86  66  72   91   65  380  76.0  21.0
學生17   76  56  90   95   55  372  74.4  25.0
學生18   54  50  72   89   64  329  65.8  45.0
學生19   73  94  84   63   69  383  76.6  18.0
學生20   95  55  53   59   79  341  68.2  39.0
學生21   88  50  97   55   50  340  68.0  40.0
學生22   97  50  81   66   74  368  73.6  29.0
學生23   93  63  57   81   72  366  73.2  32.0
學生24   55  65  57   98   86  361  72.2  33.0
學生25   98  76  74   77   74  399  79.8  12.0
學生26   93  83  93   57   96  422  84.4   5.0
學生27   85  63  65   97   95  405  81.0  10.0
學生28   87  67  66   72   81  373  74.6  24.0
學生29  100  58  65   61   72  356  71.2  36.0
學生30   86  51  51   54   67  309  61.8  49.0
學生31   71  53  65   67   94  350  70.0  38.0
學生32   91  73  64   69   72  369  73.8  28.0
學生33   53  53  81   85   50  322  64.4  47.0
學生34   73  84  60   71   51  339  67.8  41.0
學生35   61  94  94  100   77  426  85.2   4.0
學生36   77  80  73   85   59  374  74.8  23.0
學生37   72  71  88   90   84  405  81.0  10.0
學生38   86  61  56   69   66  338  67.6  43.0
學生39   55  94  98   52   99  398  79.6  13.0
學生40   54  94  71   83   88  390  78.0  16.0
學生41   91  58  97   71   89  406  81.2   9.0
學生42   63  74  95   73   77  382  76.4  19.0
學生43   52  55  64   62   56  289  57.8  50.0
學生44   75  64  66   56   90  351  70.2  37.0
學生45   97  52  63   50   57  319  63.8  48.0
學生46   63  86  77  100   70  396  79.2  15.0
學生47   91  65  67   51   87  361  72.2  33.0
學生48   67  87  81   80   53  368  73.6  29.0
學生49   60  82  96   73   87  398  79.6  13.0
學生50   85  88  80   92   94  439  87.8   2.0

In [2]:
#選擇欄位
df1 = df[["國文", "英文", "數學", "自然", "社會"]]
df1

科目     國文  英文  數學   自然   社會
學生
學生1    77  88  78   83   62
學生2    73  75  54   55   73
學生3    62  83  66  100   70
學生4    77  99  54   94   90
學生5    91  97  50   59   74
學生6    81  80  67   52   98
學生7    51  92  99   54   61
學生8    68  97  50   89   64
學生9    75  92  72   73  100
學生10   56  81  72   69   61
學生11   90  82  73   99   89
學生12  100  92  93   73   82
學生13   83  63  98   99   77
學生14   86  88  62   85   50
學生15   63  53  61   94   54
學生16   86  66  72   91   65
學生17   76  56  90   95   55
學生18   54  50  72   89   64
學生19   73  94  84   63   69
學生20   95  55  53   59   79
學生21   88  50  97   55   50
學生22   97  50  81   66   74
學生23   93  63  57   81   72
學生24   55  65  57   98   86
學生25   98  76  74   77   74
學生26   93  83  93   57   96
學生27   85  63  65   97   95
學生28   87  67  66   72   81
學生29  100  58  65   61   72
學生30   86  51  51   54   67
學生31   71  53  65   67   94
學生32   91  73  64   69   72
學生33   53  53  81   85   50
學生34   73  84  60   71   51
學生35   61  94  94  100   77
學生36   77  80  73   85   59
學生37   72  71  88   90   84
學生38   86  61  56   69   66
學生39   55  94  98   52   99
學生40   54  94  71   83   88
學生41   91  58  97   71   89
學生42   63  74  95   73   77
學生43   52  55  64   62   56
學生44   75  64  66   56   90
學生45   97  52  63   50   57
學生46   63  86  77  100   70
學生47   91  65  67   51   87
學生48   67  87  81   80   53
學生49   60  82  96   73   87
學生50   85  88  80   92   94

In [22]:
s = df1.loc["學生4"]
less_than_60_series = s[s < 60]
#取出不及格的科目
failed_subjects = less_than_60_series.index.tolist()
failed_subjects
#取出不及格的科目分數
failed_subject_scores = less_than_60_series.values.tolist()
failed_subject_scores
#建立一個Series,值要轉換為字串,若有多值則用逗號分隔
failed_subjects = ', '.join(failed_subjects)
failed_subject_scores = ', '.join(map(str, failed_subject_scores))
#建立一個Series,索引為["科目", "分數"]
result_series = pd.Series([failed_subjects, failed_subject_scores], index=["未及格科目", "分數"])
result_series

未及格科目    數學
分數       54
dtype: object

In [26]:
def apply_statistics(s):
    less_than_60_series = s[s < 60]
    #不及格科目數量
    failed_subject_count = less_than_60_series.count()
    #取出不及格的科目
    failed_subjects = less_than_60_series.index.tolist()

    #取出不及格的科目分數
    failed_subject_scores = less_than_60_series.values.tolist()
    
    #建立一個Series,值要轉換為字串,若有多值則用逗號分隔
    failed_subjects = ', '.join(failed_subjects)
    failed_subject_scores = ', '.join(map(str, failed_subject_scores))
    return pd.Series([failed_subject_count, failed_subjects, failed_subject_scores], index=["不及格科目數量","未及格科目", "分數"])

df2 = df1.apply(apply_statistics,axis=1)
df2

      不及格科目數量       未及格科目          分數
學生
學生1         0
學生2         2      數學, 自然      54, 55
學生3         0
學生4         1          數學          54
學生5         2      數學, 自然      50, 59
學生6         1          自然          52
學生7         2      國文, 自然      51, 54
學生8         1          數學          50
學生9         0
學生10        1          國文          56
學生11        0
學生12        0
學生13        0
學生14        1          社會          50
學生15        2      英文, 社會      53, 54
學生16        0
學生17        2      英文, 社會      56, 55
學生18        2      國文, 英文      54, 50
學生19        0
學生20        3  英文, 數學, 自然  55, 53, 59
學生21        3  英文, 自然, 社會  50, 55, 50
學生22        1          英文          50
學生23        1          數學          57
學生24        2      國文, 數學      55, 57
學生25        0
學生26        1          自然          57
學生27        0
學生28        0
學生29        1          英文          58
學生30        3  英文, 數學, 自然  51, 51, 54
學生31        1          英文          53
學生32        0
學生33        3  國文, 英文, 社會  53, 53, 50
學生34        1          社會          51
學生35        0
學生36        1          社會          59
學生37        0
學生38        1          數學          56
學生39        2      國文, 自然      55, 52
學生40        1          國文          54
學生41        1          英文          58
學生42        0
學生43        3  國文, 英文, 社會  52, 55, 56
學生44        1          自然          56
學生45        3  英文, 自然, 社會  52, 50, 57
學生46        0
學生47        1          自然          51
學生48        1          社會          53
學生49        0
學生50        0

In [24]:
#df和df2合併
df_merged = pd.concat([df, df2], axis=1)
df_merged

       國文  英文  數學   自然   社會   總分    平均    排名  不及格科目數量       未及格科目          分數
學生
學生1    77  88  78   83   62  388  77.6  17.0        0
學生2    73  75  54   55   73  330  66.0  44.0        2      數學, 自然      54, 55
學生3    62  83  66  100   70  381  76.2  20.0        0
學生4    77  99  54   94   90  414  82.8   7.0        1          數學          54
學生5    91  97  50   59   74  371  74.2  26.0        2      數學, 自然      50, 59
學生6    81  80  67   52   98  378  75.6  22.0        1          自然          52
學生7    51  92  99   54   61  357  71.4  35.0        2      國文, 自然      51, 54
學生8    68  97  50   89   64  368  73.6  29.0        1          數學          50
學生9    75  92  72   73  100  412  82.4   8.0        0
學生10   56  81  72   69   61  339  67.8  41.0        1          國文          56
學生11   90  82  73   99   89  433  86.6   3.0        0
學生12  100  92  93   73   82  440  88.0   1.0        0
學生13   83  63  98   99   77  420  84.0   6.0        0
學生14   86  88  62   85   50  371  74.2  26.0        1          社會          50
學生15   63  53  61   94   54  325  65.0  46.0        2      英文, 社會      53, 54
學生16   86  66  72   91   65  380  76.0  21.0        0
學生17   76  56  90   95   55  372  74.4  25.0        2      英文, 社會      56, 55
學生18   54  50  72   89   64  329  65.8  45.0        2      國文, 英文      54, 50
學生19   73  94  84   63   69  383  76.6  18.0        0
學生20   95  55  53   59   79  341  68.2  39.0        3  英文, 數學, 自然  55, 53, 59
學生21   88  50  97   55   50  340  68.0  40.0        3  英文, 自然, 社會  50, 55, 50
學生22   97  50  81   66   74  368  73.6  29.0        1          英文          50
學生23   93  63  57   81   72  366  73.2  32.0        1          數學          57
學生24   55  65  57   98   86  361  72.2  33.0        2      國文, 數學      55, 57
學生25   98  76  74   77   74  399  79.8  12.0        0
學生26   93  83  93   57   96  422  84.4   5.0        1          自然          57
學生27   85  63  65   97   95  405  81.0  10.0        0
學生28   87  67  66   72   81  373  74.6  24.0        0
學生29  100  58  65   61   72  356  71.2  36.0        1          英文          58
學生30   86  51  51   54   67  309  61.8  49.0        3  英文, 數學, 自然  51, 51, 54
學生31   71  53  65   67   94  350  70.0  38.0        1          英文          53
學生32   91  73  64   69   72  369  73.8  28.0        0
學生33   53  53  81   85   50  322  64.4  47.0        3  國文, 英文, 社會  53, 53, 50
學生34   73  84  60   71   51  339  67.8  41.0        1          社會          51
學生35   61  94  94  100   77  426  85.2   4.0        0
學生36   77  80  73   85   59  374  74.8  23.0        1          社會          59
學生37   72  71  88   90   84  405  81.0  10.0        0
學生38   86  61  56   69   66  338  67.6  43.0        1          數學          56
學生39   55  94  98   52   99  398  79.6  13.0        2      國文, 自然      55, 52
學生40   54  94  71   83   88  390  78.0  16.0        1          國文          54
學生41   91  58  97   71   89  406  81.2   9.0        1          英文          58
學生42   63  74  95   73   77  382  76.4  19.0        0
學生43   52  55  64   62   56  289  57.8  50.0        3  國文, 英文, 社會  52, 55, 56
學生44   75  64  66   56   90  351  70.2  37.0        1          自然          56
學生45   97  52  63   50   57  319  63.8  48.0        3  英文, 自然, 社會  52, 50, 57
學生46   63  86  77  100   70  396  79.2  15.0        0
學生47   91  65  67   51   87  361  72.2  33.0        1          自然          51
學生48   67  87  81   80   53  368  73.6  29.0        1          社會          53
學生49   60  82  96   73   87  398  79.6  13.0        0
學生50   85  88  80   92   94  439  87.8   2.0        0